# Generated by Django 2.2.5 on 2019-11-22 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20191121_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=80, unique=True)),
                ('course_discription', models.CharField(max_length=800)),
                ('course_url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(max_length=10)),
                ('lesson_name', models.CharField(blank=True, max_length=50)),
                ('lesson_url', models.CharField(max_length=30)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Course')),
            ],
        ),
    ]
