# Generated by Django 2.2.5 on 2019-11-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_course_courselesson_usercourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourses',
            name='course_progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
