# Generated by Django 2.2.5 on 2019-11-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20191122_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseLesson',
        ),
        migrations.DeleteModel(
            name='UserCourses',
        ),
    ]
