# Generated by Django 2.2 on 2019-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=37)),
                ('link', models.URLField(blank=True)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
