# Generated by Django 2.2 on 2019-12-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_passwordtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
