# Generated by Django 2.2.5 on 2019-11-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20191122_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Course'),
        ),
    ]
