# Generated by Django 2.2.5 on 2019-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20191123_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='profile_pics'),
        ),
    ]
