# Generated by Django 2.2 on 2019-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
