# Generated by Django 2.2 on 2019-12-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
