# Generated by Django 2.2.5 on 2019-11-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='lesson_number',
        ),
    ]
